In [1]:
import numpy as np
def nprint(arr):
    #print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n",arr)

<h1> Numpy 연습 문제 정답

<h3>문제1. 길이가 10인 0-벡터를 만드세요.

In [2]:
#배열 길이 : 일차원의 배열 길이
a=np.random.random((10,))
len(a)

10

<h3>문제2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
a=np.zeros((10,))
a[4]=1
nprint(a)
len(a)

shape:(10,), dimension:1, dtype:float64
Array's Data:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


10

<h3>문제3. 10부터 49까지의 값을 가지는 벡터를 만드세요.

In [4]:
a=np.arange(10,50,dtype=int)
nprint(a)

shape:(40,), dimension:1, dtype:int64
Array's Data:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<h3>문제4. 위 벡터의 순서를 바꾸세요.

In [5]:
np.random.shuffle(a)
nprint(a)

shape:(40,), dimension:1, dtype:int64
Array's Data:
 [46 16 23 42 31 18 35 47 21 43 38 12 30 27 17 11 25 22 41 26 40 10 32 33
 39 45 15 24 36 48 29 44 37 14 34 19 49 20 28 13]


<h3>문제5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [6]:
a=np.arange(0,9,dtype=int).reshape((3,3))
nprint(a)

shape:(3, 3), dimension:2, dtype:int64
Array's Data:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


<h3>문제6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [7]:
arr=[1,2,0,0,4,0]
a=np.array(arr)
nprint(a)

natural_num = a!=0
b=np.array(a[natural_num])
nprint(b)

shape:(6,), dimension:1, dtype:int64
Array's Data:
 [1 2 0 0 4 0]
shape:(3,), dimension:1, dtype:int64
Array's Data:
 [1 2 4]


<h3>문제7. 3x3 단위 행렬을 만드세요.

In [8]:
a=np.eye(3)
nprint(a)

shape:(3, 3), dimension:2, dtype:float64
Array's Data:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h3>문제8. 난수 원소를 가지는 3x3 행렬을 만드세요.

In [9]:
a=np.random.random((3,3))
nprint(a)

shape:(3, 3), dimension:2, dtype:float64
Array's Data:
 [[0.81430511 0.61035041 0.99337849]
 [0.90323275 0.5111103  0.22267651]
 [0.57991213 0.43665396 0.41743506]]


<h3>문제9. 위에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [10]:
#최대값
a.max(), np.max(a)

(0.9933784929730759, 0.9933784929730759)

In [11]:
#최소값
a.min(), np.min(a)

(0.22267651074071015, 0.22267651074071015)

<h3>문제10. 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하시오.

In [12]:
#행 평균
a.mean(axis=1),np.mean(a,axis=1)

(array([0.80601134, 0.54567319, 0.47800038]),
 array([0.80601134, 0.54567319, 0.47800038]))

In [13]:
#열 평균
a.mean(axis=0),np.mean(a,axis=0)

(array([0.76581666, 0.51937156, 0.54449669]),
 array([0.76581666, 0.51937156, 0.54449669]))

<h3>[추가Numpy 100문제

$ git clone https://github.com/rougier/numpy-100.git